# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c663eda7af9b0a5aa3da197ef8cfff3b8755e12f9074e6ed53e4d422dd136fea75c530eee2b2ae92841d311b16b62f485056f07324bce616e0f2a14449a677c

test:
  secret_key_base: 281e86812a657a82b284d40bf6f9957d9fe05740c2b023195c0ad4243d4392d658434ccbc418a5b263dc213d22440b07b25c55d46097f2ebee8c77cf8ffb4aa0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
